chore: Update the error checking on JWT decode
Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/007-user-test-chewie-connection.yaml b/.github/workflows/007-user-test-chewie-connection.yaml
--- a/.github/workflows/007-user-test-chewie-connection.yaml
+++ b/.github/workflows/007-user-test-chewie-connection.yaml
@@ -63,6 +63,11 @@ jobs:
             exit 1
           fi
 
+          if [[ "${CHEWIE_JWT}" == Error* ]]; then
+            echo "Failed to decode Chewie JWT: ${CHEWIE_JWT}"
+            exit 1
+          fi
+
           echo "Chewie JWT (len): ${#CHEWIE_JWT}"
           echo "Chewie JWT Expiration: ${CHEWIE_EXPIRATION}"
 
diff --git a/.github/workflows/859-call-create-chewie-request.yaml b/.github/workflows/859-call-create-chewie-request.yaml
--- a/.github/workflows/859-call-create-chewie-request.yaml
+++ b/.github/workflows/859-call-create-chewie-request.yaml
@@ -141,11 +141,15 @@ jobs:
           JWT_EXPIRY: ${{ inputs.token-expiry }}
         run: |
           CHEWIE_JWT=$(.github/workflows/support/chewie/decode-b64-jwt.sh "${CHEWIE_JWT_B64}")
+          if [[ "${CHEWIE_JWT}" == Error* ]]; then
+            echo "Failed to decode Chewie JWT: ${CHEWIE_JWT}"
+            exit 1
+          fi
 
           request_body=$(.github/workflows/support/chewie/build-compute-request.sh \
             -q "${INSTANCES_CN_QTY}" \
-            -c "${INSTANCE_CN_CPU}" \
-            -m "${INSTANCE_CN_MEMORY_MB}" \
+            -c "${INSTANCES_CN_CPU}" \
+            -m "${INSTANCES_CN_MEMORY_MB}" \
             -g "${INSTANCES_CN_GROUP_NAME}" \
             -a "${INSTANCES_AUX_QTY}" \
             -p "${INSTANCES_AUX_CPU}" \
